import {
  Package,
  Wrench,
  Truck,
  HardHat,
  Hammer,
  Cog,
  MapPin,
  Recycle,
  Snowflake,
  Droplets,
  Zap,
  Trash2,
  Container,
  Box,
  Boxes,
  Building2,
  Factory,
  TreePine,
  Leaf,
  Flame,
  Wind,
  Sun,
  CloudRain,
  Shovel,
  Paintbrush,
  Brush,
  Drill,
  Forklift,
  Car,
  Bus,
  Bike,
  Ship,
  Plane,
  Fuel,
  Battery,
  Lightbulb,
  Plug,
  Settings,
  ClipboardCheck,
  ClipboardList,
  FileText,
  Camera,
  Bell,
  Flag,
  Star,
  Heart,
  Shield,
  Key,
  Lock,
  Phone,
  Mail,
  User,
  Users,
  Home,
  Warehouse,
  Store,
  ShoppingCart,
  Tag,
  Tags,
  Calendar,
  Clock,
  Timer,
  Gauge,
  Thermometer,
  Scale,
  Ruler,
  Wifi,
  Radio,
  type LucideIcon,
} from "lucide-react";

// Centralt ikonregister (Task #942): mappar Lucide-namn (kebab-case eller PascalCase)
// till komponenter. Används av ikonregistret (admin) och alla ytor som visar ikoner.
const ICON_MAP: Record<string, LucideIcon> = {
  package: Package,
  wrench: Wrench,
  truck: Truck,
  "hard-hat": HardHat,
  hammer: Hammer,
  cog: Cog,
  "map-pin": MapPin,
  recycle: Recycle,
  snowflake: Snowflake,
  droplets: Droplets,
  zap: Zap,
  "trash-2": Trash2,
  trash: Trash2,
  container: Container,
  box: Box,
  boxes: Boxes,
  "building-2": Building2,
  building: Building2,
  factory: Factory,
  "tree-pine": TreePine,
  leaf: Leaf,
  flame: Flame,
  wind: Wind,
  sun: Sun,
  "cloud-rain": CloudRain,
  shovel: Shovel,
  paintbrush: Paintbrush,
  brush: Brush,
  drill: Drill,
  forklift: Forklift,
  car: Car,
  bus: Bus,
  bike: Bike,
  ship: Ship,
  plane: Plane,
  fuel: Fuel,
  battery: Battery,
  lightbulb: Lightbulb,
  plug: Plug,
  settings: Settings,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "file-text": FileText,
  camera: Camera,
  bell: Bell,
  flag: Flag,
  star: Star,
  heart: Heart,
  shield: Shield,
  key: Key,
  lock: Lock,
  phone: Phone,
  mail: Mail,
  user: User,
  users: Users,
  home: Home,
  warehouse: Warehouse,
  store: Store,
  "shopping-cart": ShoppingCart,
  tag: Tag,
  tags: Tags,
  calendar: Calendar,
  clock: Clock,
  timer: Timer,
  gauge: Gauge,
  thermometer: Thermometer,
  scale: Scale,
  ruler: Ruler,
  wifi: Wifi,
  radio: Radio,
};

export const DEFAULT_ICON_NAME = "package";

// Returnerar en Lucide-komponent för ett ikonnamn, med säker fallback.
export function getLucideIconByName(name: string | null | undefined): LucideIcon {
  if (!name) return Package;
  return ICON_MAP[name] || ICON_MAP[name.toLowerCase()] || Package;
}

// Alias-nycklar som pekar på samma ikon som en kanonisk nyckel — uteslut ur väljaren.
const ICON_ALIASES = new Set(["trash", "building"]);

// Kurerad lista av valbara ikoner för ikon-väljaren (admin).
export const ICON_PICKER_OPTIONS: { value: string; Icon: LucideIcon }[] = Object.entries(ICON_MAP)
  .filter(([key]) => !ICON_ALIASES.has(key))
  .map(([value, Icon]) => ({ value, Icon }));
